### ISSUE TITLE
2.0.3 with build warning fix?

### ISSUE THREAD

**Issue by apontious-gl** [sberrevoets/SDCAutoLayout#4]
Could you do a 2.0.3 update with the build warning fix?

It's very minor, I'll understand if you don't want to go through the trouble, but it would make my life a little easier if you do.

Thanks,

**Comment by sberrevoets** [comment]
Absolutely, should have done that in the first place. Expect an update soon :smiley:

**Comment by sberrevoets** [comment]
Just pushed 2.0.3 to CocoaPods
